# Neighborhoods organized by borough
neighborhoods = {
    "Manhattan": [
        {"name": "Harlem", 
         "hint": "Known for its rich African-American culture and the Apollo Theater.",
         "extra_hint": f"Starts with 'H' and has {len('Harlem')} letters."},
        {"name": "Chelsea", 
         "hint": "Famous for art galleries and the High Line.",
         "extra_hint": f"Starts with 'C' and has {len('Chelsea')} letters."},
        {"name": "SoHo", 
         "hint": "Name stands for 'South of Houston Street', full of boutiques and lofts.",
         "extra_hint": f"Starts with 'S' and has {len('SoHo')} letters."},
        {"name": "Tribeca", 
         "hint": "Hosts a major film festival and is known for cobblestone streets.",
         "extra_hint": f"Starts with 'T' and has {len('Tribeca')} letters."},
        {"name": "Inwood", 
         "hint": "Northern tip of Manhattan, near Inwood Hill Park.",
         "extra_hint": f"Starts with 'I' and has {len('Inwood')} letters."},
        {"name": "Battery Park", 
         "hint": "Located at Manhattan’s southern tip, near ferries to the Statue of Liberty.",
         "extra_hint": f"Starts with 'B' and has {len('Battery Park'.replace(' ', ''))} letters (excluding space)."},
        {"name": "Upper East Side", 
         "hint": "Known for luxury shopping and Museum Mile.",
         "extra_hint": f"Starts with 'U' and has {len('Upper East Side'.replace(' ', ''))} letters (excluding spaces)."},
        {"name": "Washington Heights", 
         "hint": "Home to the Cloisters and large Dominican population.",
         "extra_hint": f"Starts with 'W' and has {len('Washington Heights'.replace(' ', ''))} letters (excluding spaces)."}
    ],
    "Brooklyn": [
        {"name": "Williamsburg", 
         "hint": "Hipster central with street art and indie music.",
         "extra_hint": f"Starts with 'W' and has {len('Williamsburg')} letters."},
        {"name": "Bushwick", 
         "hint": "Rising art scene and former industrial vibe.",
         "extra_hint": f"Starts with 'B' and has {len('Bushwick')} letters."},
        {"name": "Park Slope", 
         "hint": "Family-friendly with historic brownstones.",
         "extra_hint": f"Starts with 'P' and has {len('Park Slope'.replace(' ', ''))} letters (excluding space)."},
        {"name": "DUMBO", 
         "hint": "Acronym for 'Down Under the Manhattan Bridge Overpass'.",
         "extra_hint": f"Starts with 'D' and has {len('DUMBO')} letters."},
        {"name": "Flatbush", 
         "hint": "Diverse area known for Caribbean culture.",
         "extra_hint": f"Starts with 'F' and has {len('Flatbush')} letters."},
        {"name": "Crown Heights", 
         "hint": "Known for the West Indian Day Parade.",
         "extra_hint": f"Starts with 'C' and has {len('Crown Heights'.replace(' ', ''))} letters (excluding space)."},
        {"name": "Red Hook", 
         "hint": "Isolated waterfront area with great lobster rolls.",
         "extra_hint": f"Starts with 'R' and has {len('Red Hook'.replace(' ', ''))} letters (excluding space)."}
    ],
    "Queens": [
        {"name": "Astoria", 
         "hint": "Famous for Greek food and museums.",
         "extra_hint": f"Starts with 'A' and has {len('Astoria')} letters."},
        {"name": "Flushing", 
         "hint": "Home to a large Chinatown and the Mets stadium.",
         "extra_hint": f"Starts with 'F' and has {len('Flushing')} letters."},
        {"name": "Jamaica", 
         "hint": "Major transit hub with cultural diversity.",
         "extra_hint": f"Starts with 'J' and has {len('Jamaica')} letters."},
        {"name": "Forest Hills", 
         "hint": "Tennis history and Tudor-style homes.",
         "extra_hint": f"Starts with 'F' and has {len('Forest Hills'.replace(' ', ''))} letters (excluding space)."},
        {"name": "Long Island City", 
         "hint": "Rapidly developing with art spaces and skyscrapers.",
         "extra_hint": f"Starts with 'L' and has {len('Long Island City'.replace(' ', ''))} letters (excluding spaces)."},
        {"name": "Sunnyside", 
         "hint": "Known for its historic gardens and quiet streets.",
         "extra_hint": f"Starts with 'S' and has {len('Sunnyside')} letters."}
    ],
    "Bronx": [
        {"name": "Fordham", 
         "hint": "Home to Fordham University and the Bronx Zoo.",
         "extra_hint": f"Starts with 'F' and has {len('Fordham')} letters."},
        {"name": "Riverdale", 
         "hint": "Leafy suburban-style neighborhood near the Hudson.",
         "extra_hint": f"Starts with 'R' and has {len('Riverdale')} letters."},
        {"name": "Mott Haven", 
         "hint": "Up-and-coming arts district.",
         "extra_hint": f"Starts with 'M' and has {len('Mott Haven'.replace(' ', ''))} letters (excluding space)."},
        {"name": "Pelham Bay", 
         "hint": "Next to NYC’s largest park—Pelham Bay Park.",
         "extra_hint": f"Starts with 'P' and has {len('Pelham Bay'.replace(' ', ''))} letters (excluding space)."},
        {"name": "Belmont", 
         "hint": "Known as the Bronx’s Little Italy.",
         "extra_hint": f"Starts with 'B' and has {len('Belmont')} letters."}
    ],
    "Staten Island": [
        {"name": "St. George", 
         "hint": "Staten Island Ferry terminal and harbor views.",
         "extra_hint": f"Starts with 'S' and has {len('St. George'.replace(' ', '').replace('.', ''))} letters (excluding space and period)."},
        {"name": "Tottenville", 
         "hint": "Southernmost neighborhood in NYC.",
         "extra_hint": f"Starts with 'T' and has {len('Tottenville')} letters."},
        {"name": "Great Kills", 
         "hint": "Known for its marina and natural beauty.",
         "extra_hint": f"Starts with 'G' and has {len('Great Kills'.replace(' ', ''))} letters (excluding space)."},
        {"name": "New Dorp", 
         "hint": "One of the oldest Staten Island settlements.",
         "extra_hint": f"Starts with 'N' and has {len('New Dorp'.replace(' ', ''))} letters (excluding space)."},
        {"name": "Stapleton", 
         "hint": "Historic district with a waterfront redevelopment.",
         "extra_hint": f"Starts with 'S' and has {len('Stapleton')} letters."}
    ]
}



subway_lines = [
    {"line": "1", "start": "Van Cortlandt Park-242 St", "end": "South Ferry"},
    {"line": "2", "start": "Wakefield-241 St", "end": "Flatbush Ave-Brooklyn College"},
    {"line": "3", "start": "Harlem-148 St", "end": "New Lots Ave"},
    {"line": "4", "start": "Woodlawn", "end": "Crown Heights-Utica Ave"},
    {"line": "5", "start": "Eastchester-Dyre Ave", "end": "Flatbush Ave-Brooklyn College"},
    {"line": "6", "start": "Pelham Bay Park", "end": "Brooklyn Bridge-City Hall"},
    {"line": "7", "start": "Flushing-Main St", "end": "34 St-Hudson Yards"},
    {"line": "A", "start": "Inwood-207 St", "end": "Far Rockaway-Mott Ave"},
    {"line": "C", "start": "168 St", "end": "Euclid Ave"},
    {"line": "E", "start": "World Trade Center", "end": "Jamaica Center-Parsons/Archer"},
    {"line": "B", "start": "Bedford Park Blvd", "end": "Brighton Beach"},
    {"line": "D", "start": "Norwood-205 St", "end": "Coney Island-Stillwell Av"},
    {"line": "F", "start": "Jamaica-179 St", "end": "Coney Island-Stillwell Av"},
    {"line": "M", "start": "Middle Village-Metropolitan Av", "end": "Forest Hills-71 Av"},
    {"line": "N", "start": "Astoria-Ditmars Blvd", "end": "Coney Island-Stillwell Av"},
    {"line": "Q", "start": "96 St", "end": "Coney Island-Stillwell Av"},
    {"line": "R", "start": "Forest Hills-71 Av", "end": "Bay Ridge-95 St"},
    {"line": "W", "start": "Astoria-Ditmars Blvd", "end": "Whitehall St-South Ferry"},
    {"line": "L", "start": "8 Av", "end": "Canarsie-Rockaway Pkwy"},
    {"line": "G", "start": "Court Sq", "end": "Church Av"},
    {"line": "J", "start": "Broad St", "end": "Jamaica Center-Parsons/Archer"},
    {"line": "Z", "start": "Broad St", "end": "Jamaica Center-Parsons/Archer"},
]

